
List <Map<String,dynamic>> allFoods=[
  {
    "item": "Pav Bhaji ",
    "price": 80,
    "rating": 4.7,
    "quantity": "1 Plate",
    "thumbnail": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQXSNUnAKrYH9YBG4LQqx-kcFEDGoypTHxn6g&s",
    'quantity' :"1",
  },
  {
    "item": "Rumali Roti",
    "price":70,
    "rating": 50,
    "quantity": "1 Plate",
    "thumbnail": "https://www.greenchickchop.in/cdn/shop/files/RumaliRoti_result.webp?v=1682660083",
    'quantity' :"1",
  },
  {
    "item": "Masala Dosa",
    "price": 70,
    "rating": 4.5,
    "quantity": "1",
    "thumbnail": "https://vismaifood.com/storage/app/uploads/public/8b4/19e/427/thumb__700_0_0_0_auto.jpg",
    'quantity' :"1",
  },
  {
    "item": "Chole Bhature",
    "price": 90,
    "rating": 4.6,
    "quantity": "1 Plate",
    "thumbnail": "https://media.vogue.in/wp-content/uploads/2020/08/chole-bhature-recipe.jpg",
    'quantity' :"1",
  },
  {
    "item": "Vada Pav",
    "price": 30,
    "rating": 4.4,
    "quantity": "1",
    "thumbnail": "https://www.cookwithmanali.com/wp-content/uploads/2018/04/Vada-Pav-500x375.jpg",
    'quantity' :"1",
  },
  {
    "item": "Paneer Tikka",
    "price": 120,
    "rating": 4.9,
    "quantity": "1 Plate",
    "thumbnail": "https://www.cookwithkushi.com/wp-content/uploads/2023/02/paneer_tikka_at_home_01.jpg",
    'quantity' :"1",
  },
  {
    "item": "Samosa",
    "price": 20,
    "rating": 4.3,
    "quantity": "1",
    "thumbnail": "https://www.kitchensanctuary.com/wp-content/uploads/2023/10/Samosa-tall-FS.jpg",
    'quantity' :"1",
  },

  {
    "item": "Margherita Pizza",
    "price": 150,
    "rating": 4.5,
    "quantity": "1",
    "thumbnail": "https://bod-blog-assets.prod.cd.beachbodyondemand.com/bod-blog/wp-content/uploads/2014/09/Margherita-Pizza.HEADER-715x358.jpg",
    'quantity' :"1",
  },

  {
    "item": "Veggie Supreme Pizza",
    "price": 180,
    "rating": 4.6,
    "quantity": "1",
    "thumbnail": "https://api.pizzahut.io/v1/content/en-in/in-1/images/pizza/veggie-supreme.bc8dd369182b636ff171077efa53c344.1.jpg",
    'quantity' :"1",
  },
  {
    "item": "White Sauce Pasta",
    "price": 120,
    "rating": 4.5,
    "quantity": "1 Plate",
    "thumbnail": "https://www.cookwithmanali.com/wp-content/uploads/2018/12/White-Sauce-Pasta-676x1024.jpg",
    'quantity' :"1",
  },
  {
    "item": "Red Sauce Pasta",
    "price": 130,
    "rating": 4.6,
    "quantity": "1 Plate",
    "thumbnail": "https://crownresto.com/wp-content/uploads/2021/10/Red-Sauce-Pasta-Recipe-thumbnail-600x626.jpg",
    'quantity' :"1",
  },
  {
    "item": "Pesto Pasta",
    "price": 150,
    "rating": 4.8,
    "quantity": "1 Plate",
    "thumbnail": "https://www.dinneratthezoo.com/wp-content/uploads/2018/03/chicken-pesto-pasta-14-1.jpg",
  'quantity' :"1",
  },
  {
    "item": "Classic Veggie Burger",
    "price": 60,
    "rating": 4.2,
    "quantity": "1",
    "thumbnail": "https://www.noracooks.com/wp-content/uploads/2023/04/veggie-burgers-6-1024x1536.jpg",
  'quantity' :"1",
  },

  {
    "item": "Cheese Burger",
    "price": 70,
    "rating": 4.3,
    "quantity": "1",
    "thumbnail": "https://www.recipetineats.com/tachyon/2022/08/Stack-of-cheeseburgers.jpg?resize=900%2C1125&zoom=1",
  'quantity' :"1",
  },
  {
    "item": "Chocolate Cake",
    "price": 250,
    "rating": 4.9,
    "quantity": "1 Kg",
    "thumbnail": "https://baranbakery.com/wp-content/uploads/2022/10/Chocolate-Ganache-Cake-14.jpg",
  'quantity' :"1",
  },
  {
    "item": "Vanilla Cake",
    "price": 220,
    "rating": 4.7,
    "quantity": "1 Kg",
    "thumbnail": "https://projectveganbaking.com/wp-content/uploads/2020/08/IMG_3003.jpg",
  'quantity' :"1",
  },
  {
    "item": "Red Velvet Cake",
    "price": 280,
    "rating": 4.8,
    "quantity": "1 Kg",
    "thumbnail": "https://www.cookiedoughandovenmitt.com/wp-content/uploads/2022/01/Red-Velvet-Cake-Recipe-19-Image.jpg",
  'quantity' :"1",
  },
  {
    "item": "Classic Hot Dog",
    "price": 80,
    "rating": 4.1,
    "quantity": "1",
    "thumbnail": "https://www.cookingcarnival.com/wp-content/uploads/2022/04/Veg-hot-dog.webp",
  'quantity' :"1",
  },
  {
    "item": "Cheese Hot Dog",
    "price":90,
    "rating": 4.3,
    "quantity": "1",
    "thumbnail": "https://thebakermama.com/wp-content/uploads/2016/09/IMG_0288.jpg",
  'quantity' :"1",
  },
  {
    "item": "Classic French Fries",
    "price": 60,
    "rating": 4.5,
    "quantity": "1 Plate",
    "thumbnail": "https://www.thespruceeats.com/thmb/_uO-Y9p8eu4ZVFnNQZmVqjLPoBg=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/how-to-make-homemade-french-fries-2215971-hero-01-02f62a016f3e4aa4b41d0c27539885c3.jpg",
  'quantity' :"1",
  },
  {
    "item": "Grilled Cheese Sandwich",
    "price": 50,
    "rating": 4.4,
    "quantity": "1",
    "thumbnail": "https://assets.epicurious.com/photos/59b2bccaed60845e59e6d3d1/1:1/w_1600,c_limit/shutterstock_321217517.jpg",
  'quantity' :"1",
  },
  {
    "item": "Club Sandwich",
    "price": 100,
    "rating": 4.6,
    "quantity": "1",
    "thumbnail": "https://www.tasteandtellblog.com/wp-content/uploads/2021/07/Club-Sandwich-1-768x512.jpg",
  'quantity' :"1",
  },

  {
    "item": "Veggie Sandwich",
    "price": 70,
    "rating": 4.3,
    "quantity": "1",
    "thumbnail": "https://www.themediterraneandish.com/wp-content/uploads/2024/03/TMD-Vegetable-Sandwich-Leads-02-Vertical.jpg",
  'quantity' :"1",
  },
  {
    "item": "BLT Sandwich",
    "price": 90,
    "rating": 4.7,
    "quantity": "1",
    "thumbnail": "https://img.sndimg.com/food/image/upload/f_auto,c_thumb,q_55,w_860,ar_3:2/v1/img/recipes/12/96/15/RCNa1fLaTS2U0FY3yOUq_BLT%25205%2520-%2520final_6.jpg",
  'quantity' :"1",
  },

  {
    "item": "Plain Dosa",
    "price": 50,
    "rating": 4.2,
    "quantity": "1",
    "thumbnail": "https://www.cubesnjuliennes.com/wp-content/uploads/2023/10/Best-Crispy-Plain-Dosa-Recipe.jpg",
  'quantity' :"1",
  },
  {
    "item": "Paper Dosa",
    "price": 80,
    "rating": 4.6,
    "quantity": "1",
    "thumbnail": "https://recipes.net/wp-content/uploads/2024/01/how-to-eat-paper-dosa-1706065521.jpg",
  'quantity' :"1",
  },
  {
    "item": "Rawa Dosa",
    "price": 70,
    "rating": 4.4,
    "quantity": "1",
    "thumbnail": "https://www.maggi.in/sites/default/files/styles/home_stage_1500_700/public/srh_recipes/425104d631c6cbb36023a80f63a52bf8.jpg?h=06f6671c&itok=dPQTyf1c",
  'quantity' :"1",
  },

  {
    "item": "Mysore Masala Dosa",
    "price": 90,
    "rating": 4.7,
    "quantity": "1",
    "thumbnail": "https://www.slurrp.com/web/_next/image?url=https%3A%2F%2Fimages.slurrp.com%2Fprodarticles%2F19slsy94if2.webp%3Fimpolicy%3Dslurrp-20210601%26width%3D1200%26height%3D900%26q%3D75&w=1200&q=75",
  'quantity' :"1",
  },
  {
    "item": "Cheese Dosa",
    "price": 85,
    "rating": 4.6,
    "quantity": "1",
    "thumbnail": "https://st4.depositphotos.com/19960896/27611/i/1600/depositphotos_276117254-stock-photo-cheese-masala-dosa-recipe-sambar.jpg",
  'quantity' :"1",
  },

];

